# Generated by Django 2.2.5 on 2019-10-15 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=300)),
                ('primerapellido', models.CharField(db_column='primerApellido', max_length=300)),
                ('segundoapellido', models.CharField(blank=True, db_column='segundoApellido', max_length=300, null=True)),
                ('birthdate', models.DateField(db_column='birthDate')),
            ],
            options={
                'db_table': 'persona',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tipousuario',
            fields=[
                ('idtipousuario', models.AutoField(db_column='idTipoUsuario', primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tipousuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idusuario', models.AutoField(db_column='idUsuario', primary_key=True, serialize=False)),
                ('alias', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=300, unique=True)),
                ('passwd', models.CharField(max_length=300)),
                ('eliminado', models.TextField()),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
        ),
    ]
