# Generated by Django 2.2.5 on 2019-10-15 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrearticulo', models.CharField(db_column='nombreArticulo', max_length=250)),
                ('descripcion', models.CharField(blank=True, max_length=1000, null=True)),
                ('cantidad', models.IntegerField()),
                ('costo', models.FloatField()),
                ('eliminado', models.BooleanField()),
            ],
            options={
                'db_table': 'articulo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(max_length=300)),
                ('email', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'contacto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('idcuenta', models.AutoField(db_column='idCuenta', primary_key=True, serialize=False)),
                ('fechaingreso', models.DateTimeField(db_column='fechaIngreso')),
                ('activa', models.TextField()),
                ('eliminado', models.BooleanField()),
                ('fechasalida', models.DateTimeField(blank=True, db_column='fechaSalida', null=True)),
            ],
            options={
                'db_table': 'cuenta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cp', models.IntegerField(blank=True, null=True)),
                ('idestado', models.IntegerField(blank=True, db_column='idEstado', null=True)),
                ('idmunicipio', models.IntegerField(blank=True, db_column='idMunicipio', null=True)),
                ('idasentamiento', models.IntegerField(blank=True, db_column='idAsentamiento', null=True)),
            ],
            options={
                'db_table': 'direccion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('idstock', models.AutoField(db_column='idStock', primary_key=True, serialize=False)),
                ('fechaingreso', models.DateTimeField(db_column='fechaIngreso')),
                ('eliminado', models.BooleanField()),
                ('fechasalida', models.DateTimeField(blank=True, db_column='fechaSalida', null=True)),
            ],
            options={
                'db_table': 'stock',
                'managed': False,
            },
        ),
    ]
