# Generated by Django 2.2.5 on 2019-10-15 03:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0002_articulo_contacto_cuenta_direccion_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticuloHasKeywords',
            fields=[
                ('articulo', models.ForeignKey(db_column='Articulo_id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='src.Articulo')),
            ],
            options={
                'db_table': 'articulo_has_keywords',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ArticuloTieneCategoria',
            fields=[
                ('idarticulocategoria', models.AutoField(db_column='idArticuloCategoria', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'articulo_tiene_categoria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idcategoria', models.AutoField(db_column='idCategoria', primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'categoria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=450)),
            ],
            options={
                'db_table': 'foto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Keywords',
            fields=[
                ('idkeywords', models.AutoField(db_column='idKeyWords', primary_key=True, serialize=False)),
                ('descripcio', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'keywords',
                'managed': False,
            },
        ),
    ]
