# Generated by Django 2.2.5 on 2019-10-15 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0003_articulohaskeywords_articulotienecategoria_categoria_foto_keywords'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulohaskeywords',
            name='articulo',
        ),
        migrations.DeleteModel(
            name='ArticuloTieneCategoria',
        ),
        migrations.DeleteModel(
            name='ArticuloHasKeywords',
        ),
    ]
